### ISSUE TITLE
.gitignoreについて

### ISSUE THREAD

**Issue by take-cheeze** [chikuwait/bitvisor_mruby#2]
本当は本家に言ったほうがいい気はするんですが、
https://github.com/chikuwait/bitvisor_mruby/commit/99eb76caef799904526e67f07abcf34eb1efca54 みたいなコミットが起きないように、.gitignoreファイルを定義してあげた方がいいかなーと。
最低でも:
```
*.o
*.s
*.d
.depends
.flags

/.config
```
ですかねー。あと細々と生成されるファイルもちゃんと入れてあげた方がいいかと。

**Comment by chikuwait** [comment]
そうですね、定義しておこうと思います。
